### ISSUE TITLE
Inference on test images?

### ISSUE THREAD

**Issue by tianchen-ns** [mlpc-ucsd/LETR#1]
Hi,

Thanks for sharing the code and nice/solid works! I wonder do you have some example code for inference on the test images without ground truth? The current implementation is only for train/evaluation, and the wrapper of dataloader is with both image and target. Thank you.

**Comment by yix081** [comment]
Thanks for your interest.  I will upload one tomorrow if possible, and will keep you updated.

**Comment by tianchen-ns** [comment]
> Thanks for your interest. I will upload one tomorrow if possible, and will keep you updated.

Thank you so much. Looking forward to the update.

**Comment by yix081** [comment]
Hi, Here is a quick usage demo. Hope it helps.
https://github.com/mlpc-ucsd/LETR/blob/master/src/demo_letr.ipynb
