### ISSUE TITLE
Unused parameters warning while reproducing the results

### ISSUE THREAD

**Issue by madhu9595** [mlpc-ucsd/LETR#4]
Getting the following warning during training:

**[W reducer.cpp:1050] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters. This flag results in an extra traversal of the autograd graph every iteration, which can adversely affect performance. If your model indeed never has any unused parameters, consider turning this flag off. Note that this warning may be a false positive your model has flow control causing later iterations to have unused parameters. (function operator())**

is file **reducer.cpp** a part of back-end network and how to access and modify it ?

**Comment by yix081** [comment]
Thanks for pointing it out! This flag is used to debug our old codebase, but may not be useful in the current GitHub cleaned codebase. Feel free to turn it off if it hurts performance.
