### ISSUE TITLE
cuda out of memory error while reproducing the result

### ISSUE THREAD

**Issue by madhu9595** [mlpc-ucsd/LETR#6]
i am getting the following error while reproducing the result.

**CUDA out of memory. Tried to allocate 96.00 MiB (GPU 0; 10.76 GiB total capacity; 8.86 GiB already allocated; 64.94 MiB free; 8.99 GiB reserved in total by PyTorch).**

**raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)**

**Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.**

I have tried to reduce the batch size, image resolution and cleared pytorch cache as well; still the issue exists. Any suggestion on this would be a great help.

**Comment by yix081** [comment]
Hi, what's your hardware configuration, and which script are you running?

**Comment by madhu9595** [comment]
I am running the script on Ubuntu 18.04 machine with 2 Nvidia rtx 2080 graphic cards. The 1st stage of training goes well. I am facing issue at the 2nd stage of training while running the command **bash script/train/a2_train_stage2_res50.sh  res50_stage2** . Tried setting the **OMP_NUM_THREADS** to values other than the default value. Still the issue persists.
![image](https://user-images.githubusercontent.com/58338067/133259011-23e33e6d-9493-4d3c-8f0d-173ac87bfe90.png)

**Comment by yix081** [comment]
The 2nd stage of the LETR training requires more GPU memory. To reduce memory usage, you are welcome to try to replace self-attention with efficient attention (e.g. our Conv-Attention module in CoaT https://github.com/mlpc-ucsd/CoaT).

**Comment by madhu9595** [comment]
how much memory should be enough for training the network ?

**Comment by yix081** [comment]
We train second stage with 24GB gpus

**Comment by danishansari** [comment]
@yix081 what batch size you use for training on 24gb gpus?
